[build]
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "src"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
